### ISSUE TITLE
 Not Found - GET https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.0.tgz

### ISSUE THREAD

**Issue by jefferyvincent** [t4d-wintellectnow/apollo-react-client-state-starter-project#1]
Hello,

I am getting the following error when I try to do an npm install:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.0.tgz
npm ERR! 404 
npm ERR! 404  'flatmap-stream@0.1.0' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 It was specified as a dependency of 'apollo-react-client-state-starter-project'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by ericwgreene** [comment]
Looks like one of the packages for the project was using this package and now it has been unpublished or something.

https://www.npmjs.com/package/flatmap-stream

This would be a dependency of a dependency of a dependency issue. The starter project is not using the package directly. I will take a further look at it today or tomorrow.

FYI...

https://github.com/GoogleChromeLabs/squoosh/issues/339

**Comment by jefferyvincent** [comment]
Okay thanks, I'll check back tomorrow.

**Comment by ericwgreene** [comment]
And if I can get to it today, I will let you know. Thank you for reporting the issue!

**Comment by ericwgreene** [comment]
@jefferyvincent I just attempted to reproduce the problem but I could not. Everything installed fine. What operating system, Node version, and NPM version are you using? Can you paste the full results of your NPM install? Thanks!

PS...  Everything ran correctly for the starter project as well. I am running on a Mac with Node v10.15.1 and NPM 6.8.0.

**Comment by jefferyvincent** [comment]
Mac: 10.13.6
Node: v10.15.1
npm: 6.8.0


`$:apollo-react jevinc$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/Users/jevinc/Projects/apollo-react/node_modules/.staging/fsevents-3a199527/node_modules/set-blocking' -> '/Users/jevinc/Projects/apollo-react/node_modules/.staging/set-blocking-174c41b7'

npm ERR! code E404
npm ERR! 404 Not Found: flatmap-stream@0.1.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jevinc/.npm/_logs/2019-02-20T22_05_48_550Z-debug.log
$:apollo-react jevinc$`

In the log it says:
17092 error code E404
17093 error 404 Not Found: flatmap-stream@0.1.0

**Comment by ericwgreene** [comment]
Ahhh... Node 11... :)

Please use Node 10. As mentioned in the video, we do not upgrade to later versions of Node. I recommend using NVM to easily manage your Node versions. It's super easy to change versions.

https://github.com/creationix/nvm

Hope that helps!

Also, as a general rule, I never use non-LTS versions of Node.js for development or production. I have run into too many problems with non-LTS versions over the years.

Now, if the install fails for Node 10, please let me know. Thanks!

**Comment by jefferyvincent** [comment]
I am not using node 11. I am using the following:
Mac: 10.13.6
Node: v10.15.1
npm: 6.8.0

**Comment by ericwgreene** [comment]
@jefferyvincent Did you just change your Node version? I could have sworn it said 11.

**Comment by jefferyvincent** [comment]
Nope:

$ node -v
v10.15.1
$ npm -v
6.4.1

**Comment by jefferyvincent** [comment]
I had an older version of Node JS and I upgraded it to the one your using.

**Comment by ericwgreene** [comment]
@jefferyvincent Ok... Try this, delete **package-lock.json** and **node_modules** then use the following command to do the install:

npm install --cache /tmp/empty-cache

Let me know the results. Thanks!

**Comment by jefferyvincent** [comment]
If I take out the package-lock.json file it installs and runs fine... So maybe that's the problem all along.

**Comment by jefferyvincent** [comment]
It's working now, and I can run queries on the server. Thanks!

**Comment by ericwgreene** [comment]
@jefferyvincent Excellent! Thank you for your help! I will update the **package-lock.json** for future students.

**Comment by imkost** [comment]
> If I take out the package-lock.json file it installs and runs fine... So maybe that's the problem all along.

thanks. I had the same issue. Your advice saved me a lot of time.
