### ISSUE TITLE
issue while running client

### ISSUE THREAD

**Issue by sushilbansal** [t4d-wintellectnow/apollo-react-client-state-starter-project#2]
if i try to run: npm run start-client 
then i get this message in browser:

Error: Encountered a sub-selection on the query, but the store doesn't have an object reference. This should never happen during normal use unless you have custom code that is directly manipulating the store; please file an issue.

**Comment by ericwgreene** [comment]
Hi @sushilbansal, I am sorry you are having this problem but I have never seen this error before and I just ran the client and all worked fine. If you have more information on the problem you would like to share what would be great.

**Comment by sushilbansal** [comment]
i used yarn to install the dependencies. Could it be that? I will try to install dependencies through npm.

**Comment by ericwgreene** [comment]
Couple be yarn. Try NPM and let me know what happens! Thanks!

**Comment by sushilbansal** [comment]
Yeah it worked with npm
