### ISSUE TITLE
Can't query on toolName field 

### ISSUE THREAD

**Issue by btomlinatx** [t4d-wintellectnow/apollo-react-client-state-starter-project#3]
I'm currently working on the "Configuring and querying client state: Demo" video on LinkedIn Learning, and I'm getting an error when I try to run the query containing the `toolName` field. I get the error `Configuring and querying client state: Demo`. If I try to run the query in the Apollo Dev Tools it shows that there is no `toolName` field available to query. Is there something else I need to do to make this query work. I have the `@client` directive as well as the clientStateLink configured with the default value. Is there something I'm missing?

**Comment by btomlinatx** [comment]
Client state configuration:

```
const clientStateLink = withClientState({
  cache,
  defaults: {
    toolName: 'Widget Tool'
  },
  resolver: {},
});
```

Apollo link configuration:

```
const link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  webSocketLink,
  ApolloLink.from([ clientStateLink, httpLink ]),
);
```

Query in App.js

```
const APP_QUERY = gql`
  query App {
    toolName @client
    widgets {
      id
      name
      description
      color
      size
      price
      quantity
    }
  }
`
```

**Comment by ericwgreene** [comment]
The “resolver” property should be plural, “resolvers”. Thanks!

**Comment by btomlinatx** [comment]
d'oh. Knew it would be a typo! Thanks so much for the help.
